language: node_js
node_js:
- '8'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
# - export DISPLAY=:99.0
- npm install -g @angular/cli
script:
- ng build --prod
- ng test --single-run
notifications:
  slack:
    secure: SDE2Kn65eFDRw2D6rxrfqvA/PrLeYsBcDfxWxGRs9XnyIgBPD46/DGefBxlGsNamUVEhdQ8t5AgXujt6SHYkCDIeGdi9JzfdY75YDPGIDekWoKjR5I4pX4TYOkdoFJVwQvhiUA1LH2WVpOmt3eul5cVsfgqTMjVUaSFlOuEyeGER9+uzC2GanqLJ6TmllPRSWAoIFQPkSB59631fJsOk1551NdPNbk8FNDEMDg8HjO1a+06vv6V8SmA30vMYEfQ9u8wZwBzpv3QlCXxSNI5uQaWl/R0QopJOnFxw4MCpb4l8yXDSTz5+7l68NPbu+svTa0jqVG6IGOyrJpynH6Z0zh5aoZLWuP2WcBF8aAqTxjU6blOioGOUCOqiq/vj375y0E8OjhkNAEVTq9ojJwjY61wcZkNZz7OIjkBTDajUcWwkY2SdSfkPdEuGLzCzyCC8GHhH9p3WL7Koup3XSJUiQBEx+lUI4zzjSnJwDFbjBNpORV6wXvynW/OnhIs0nuce+/Yd01HMhbx0Np64mVbKBqkGFEFWYK1mM6eXTr+BCDJ5s7YIdWT6t0hdkgrgk6F7gJyq6apLh+EdajEAIYb/OH31lkS8SNf6ZsMz3nfQbZqKn6K9wm20hgOnkV6+NOvnbrNVByGFCRPkv2o6b1rYhNM74KC7FckMhAlDt5pRtug=
